shaders:
  - changed-files:
      - any-glob-to-any-file:
          - "shaders/**"

build-system:
  - changed-files:
      - any-glob-to-any-file:
          - "CMakeLists.txt"
          - "cmake/**"
          - "**/*.cmake"

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "dependencies/**"

render-pipeline:
  - changed-files:
      - any-glob-to-any-file:
          - "src/rhi/**"
          - "include/rhi/**"
          - "shaders/**"
          - "src/**/*render*"
          - "include/**/*render*"

stager:
  - changed-files:
      - any-glob-to-any-file:
          - "src/stager.cpp"
          - "include/stager.hpp"
          - "src/**/*stager*"
          - "include/**/*stager*"
